name = "React Router"
roles = ["frontend", "backend"]
webhooks_path = "/webhooks/app/uninstalled"

[commands]
predev = "./node_modules/.bin/prisma generate"
dev = "./node_modules/.bin/prisma migrate deploy && ./node_modules/.bin/react-router dev"
